export const roleEnum = ['user', 'admin'] as const;

export const genderEnum = ['homme', 'femme'] as const;

export const doctorateTypeEnum = ['classique', 'lmd'] as const;

export const gradesEnum = [
	'Professeur',
	'Maître de conférences classe A',
	'Maître de conférences classe B',
	'Maître assistant classe A',
	'Maître assistant classe B',
	'Directeur de recherche',
	'Chargé de recherche',
	'Maître de recherche classe A',
	'Maître de recherche classe B',
	'Attaché de recherche A',
	'Attaché de recherche B'
] as const;

export const situationProfessionnelleEnum = [
	'Maître assistant classe A',
	'Maître assistant classe B',
	'Attaché de recherche A',
	'Attaché de recherche B',
	'Salarié MESRS non enseignant',
	'Salarié hors MESRS',
	'Non salarié'
] as const;

export const domainEnum = [
	'Sciences Economiques, de Gestion et Commerciales',
	'Sciences et Technologies',
	'Mathématiques et Informatique',
	'Sciences de la Nature et de la Vie',
	'Sciences Humaines et Sociales',
	'Sciences de la Matière',
	"Sciences de la terre et de l'Univers",
	'Lettres et Langues Etrangères',
	'Langue et Littérature Arabes',
	'Droit et Sciences Politiques'
] as const;

export const filiereEnum = [
	'Sciences Economiques',
	'Electrotechnique',
	'Informatique',
	'Génie Mécanique',
	'Sciences de Gestion',
	'Sciences Agronomiques',
	'Sciences Sociales - Philosophie',
	'Electronique',
	'Télécommunications',
	'Génie des Procédés',
	'Hydraulique',
	'Mathématiques',
	'Sciences Humaines - Histoire',
	'Physique',
	'Automatique',
	'Chimie',
	'Géographie et Aménagement du Territoire',
	'Sciences Biologiques',
	'Langue Française',
	'Géologie',
	'Sciences Sociales - Sociologie',
	'Sciences Commerciales',
	'Sciences Sociales - Psychologie',
	'Biotechnologies',
	'Sciences Financières et Comptabilité',
	'Sciences Sociales',
	'Etudes Littéraires',
	'Droit',
	"Génie de l'Environnement",
	'Etudes Linguistiques',
	'Sciences Alimentaires',
	'Langue Anglaise',
	'Etudes Critiques',
	'Hydrobiologie Marine et Continentale',
	'Génie Civil',
	'Electromécanique',
	'Travaux Publics',
	'Langue et Littérature Arabes'
] as const;

export const laboratoiteRattachementEnum = [
	'Laboratoire Management des Collectivités Locales et Développement Local',
	"Laboratoire d'Analyse, de Prospective et de Développement des Emplois et des Compétences",
	'Laboratoire de PME, Recherche et Innovation',
	'Laboratoire de Chimie Organique, Macromoléculaire et des Matériaux',
	'Laboratoire des Matériaux, Applications et Environnement',
	'Laboratoire de physique quantique de la matière et modélisation mathématique',
	"Laboratoire des sciences et techniques de l'eau",
	'Laboratoire de Génie des Procédés et Chimie des Solutions',
	'Laboratoire de Recherche sur les Systèmes Biologiques et la Géomatique',
	'Laboratoire Géo Environnement et Développement des Espaces',
	'Chimie Physique des Macromolécules et Interfaces Biologiques',
	'Laboratoire de Bioconversion, Génie Microbiologique et Sécurité Sanitaire',
	'Méthodologie de la critique moderne et analyse du discours',
	"Laboratoire de l'ingénierie des programmes de langue dans les filières de spécialité",
	'Laboratoire des Recherches Sociologiques et Historiques',
	'Laboratoire Législations des Droits Economiques',
	'Les outils juridiques de la politique foncière',
	'Laboratoire de Géomatique, Ecologie et Environnement',
	'Laboratoire de Linguistique Arabe et Analyse des Textes',
	"Laboratoire d'analyse des systèmes"
] as const;

export const establishmentEnum = [
	'Université de Bouira – Akli Mohand Oulhadj',
	'Université de Djelfa – Ziane Achour',
	'Université de Ghardaia',
	'Université de Khemis Miliana – Djilali Bounaama',
	'Université Médéa – Yahia Farès',
	"Université des sciences et de la technologie d'Alger Houari Boumediène",
	'Université de Béjaia – Abderrahmane Mira',
	"Université de Boumerdès – M'hamed Bougara",
	'Université de Tizi Ouzou – Mouloud Maameri',
	'Université de Laghouat – Amar Telidji',
	'Université Blida 1 – Saad Dahlab',
	'Université de Blida 2 – Lounici Ali',
	"Université d'Alger 1 – Benyoucef Benkhedda",
	"Université d'Alger 2 – Abou el Kacem Saâdallah",
	"Université d'Alger 3 – Brahim Soltane Chaibout",
	'Université de la Formation Continue',
	'Université de Tamenghasset',
	'Université de Jijel – Mohammed Seddik Ben yahia',
	'Université de Tébessa – Larbi Tébessi',
	'Université de Bordj Bou Arréridj – Mohamed Bachir El Ibrahimi',
	"Université d'El Tarf – Chadli Bendjedid",
	'Université de Khenchela – Abbas Laghrour',
	"Université de Oum El Bouaghi – Larbi Ben M'hidi",
	"Université d'El Oued – Hamma Lakhdar",
	'Université de Souk Ahras – Mohammed-Chérif Messaadia',
	'Université de Annaba – Badji Mokhtar',
	'Université du 20 Août 1955 de Skikda',
	'Université 8 Mai 1945 de Guelma',
	'Université de Batna 1 – Hadj Lakhder',
	'Université de Biskra – Mohamed Khider',
	"Université de M'sila – Mohamed Boudiaf",
	'Université de Ouargla – Kasdi Merbah',
	'Université des sciences islamiques Emir Abdelkader de Constantine',
	'Université de Sétif 1 – Ferhat Abbas',
	'Université de Sétif 2 – Mohamed Lamine Debaghine',
	'Université de Constantine 1 – Frères Mentouri',
	'Université de Constantine 2 – Abdelhamid Mehri',
	'Université de Constantine 3 – Salah Boubnider',
	'Université de Batna 2 – Mustapha Ben Boulaid',
	'Université de Béchar – Mohamed Tahri',
	'Université de Mascara – Mustapha Stambouli',
	'Université de Saida – Tahar Moulay',
	'Université de Tlemcen – Abou Bekr Belkaid',
	"Université d'Adrar – Ahmed Draya",
	'Université de Tiaret – Ibn Khaldoun',
	'Université Sidi Bel Abbès – Djillali Liabes',
	'Université de Mostaganem – Abdelhamid Ibn Badis',
	"Universitéd'Oran1 – Ahmed Ben Bella",
	"Université Mohamed Boudiaf des sciences et de la technologie – Mohamed Boudiaf d'Oran",
	"Université d'Oran 2 – Mohamed Ben Ahmed",
	'Université de Chlef – Hassiba Benbouali',
	'Université de Tissemsilt',
	'Université de Aïn Témouchent',
	'Université de Relizane',
	'Ecole Nationale Polytechnique',
	"Ecole nationale supérieure d'hydraulique – Arbaoui Abdellah",
	'Ecole nationale supérieure des travaux publics – Francis Jeanson',
	'Ecole nationale supérieure vétérinaire – Rabie Bouchama',
	"Ecole Polytechnique d'architecture et d'Urbanisme-Hocine Aït Ahmed",
	'Ecole nationale supérieure agronomique- Khalef Abdellah alias Kasdi Merbah',
	'Ecole des hautes études commerciales',
	"Ecole nationale supérieure d'informatique",
	'Ecole nationale supérieure en statistique et en économie appliquée',
	'Ecole Supérieure de Commerce-Mouloud Kacem Naït Belkacem',
	"Ecole nationale supérieure des sciences de la mer et de l'aménagement du littoral",
	'Ecole nationale supérieure de management',
	'Ecole Nationale Supérieure de Technologie',
	"Ecole nationale supérieure de journalisme et des sciences de l'information",
	'Ecole Nationale Supérieure des sciences politiques',
	"Ecole Supérieure des Sciences de l'Aliment et des Industries Agroalimentaires d'Alger ex EP SNV Alger",
	"Ecole Supérieure des Sciences appliquées d'Alger ex EP ST Alger",
	"Ecole Supérieure de Gestion et d'Economie Numérique",
	"École Supérieure en Sciences et Technologies de l'Informatique et du Numérique de Bejaia",
	'École Nationale Supérieure en Intelligence Artificielle',
	'École Nationale Supérieure en Mathématique',
	'Ecole Nationale Supérieure des Technologies Avancées',
	'Ecole nationale supérieure des mines et de la métallurgie – Amar Laskri',
	'Ecole Nationale Polytechnique de Constantine- Malek Bennabi',
	'Ecole Nationale Supérieure de Biotechnologie de Constantine – Tewfik Khaznadar',
	'Ecole Supérieure des Sciences de Gestion de Annaba ex – EPSECG Annaba',
	'Ecole Supérieure des Technologies Industrielles de Annaba ex EP ST Annaba',
	'Ecole Supérieure de Comptabilité et de Finance de Constantine ex EPSECG Constantine',
	'École nationale supérieure des forêts – Khenchela',
	"L'Ecole nationale supérieure des énergies renouvelables environnement et développement durable – Batna",
	"L'Ecole supérieure de l'agriculture saharienne – El Oued",
	"Ecole Nationale Polytechnique d'Oran – Maurice Audin",
	"Ecole Supérieure d'Informatique (Sidi Bel Abbes)- 8 Mai 1945",
	'Ecole Supérieure des Sciences Appliquées de Tlemcen ex EP ST Tlemcen',
	'Ecole Supérieure de Management de Tlemcen ex EPSECG Tlemcen',
	"Ecole Supérieure d'Economie d'Oran ex EPSECG Oran",
	"Ecole Supérieure en Génie Electrique et Energétique d'Oran ex EP ST Oran",
	'Ecole Supérieure Agronomique de Mostaganem ex EP SNV Mostaganem',
	"Ecole Supérieure des sciences Biologiques d' Oran ex EP SNV Oran",
	"L'Ecoles supérieures de l'agriculture saharienne – Adrar",
	'Ecole normale supérieure de Bouzaréah – Cheikh Mubarak Ben Mohamed Brahimi El Mili',
	'Ecole normale supérieure de Kouba – Mohamed Bachir El Ibrahimi',
	'Ecole normale supérieure de Laghouat – Taleb Abderrahmane',
	'Ecole normale supérieure de sourds muets',
	'Ecole normale supérieure de Constantine Assia Djebar',
	"Ecole normale supérieure d'enseignement technologique de Skikda",
	'Ecole normale supérieure de setif – Messaoud Zeghar',
	'Ecole normale supérieure de Bou Saâda',
	'Ecole normale supérieure de Ouargla',
	'Ecole Normale Supérieure de Mostaganem',
	"Ecole Normale Supérieure d'Oran",
	'Ecole normale supérieure de Béchar',
	'Centre universitaire de Tipaza – Abdallah Morsli',
	"Centre Universitaire d'Illizi-Cheikh Amoud ben Mokhtar",
	"Centre universitaire d'Aflou",
	'Centre Universitaire de Mila – Abdelhafid Boussouf',
	'Centre Universitaire de Barika – Si El Haouès',
	'Centre universitaire de Naama – Ahmed Salhi',
	"Centre universitaire d'El Bayadh – Nour Bachir",
	'Centre universitaire de Tindouf-Ali Kafi',
	'Centre universitaire de Maghnia'
] as const;
// options object layout for select/radio inputs

function enumToOption(arr: readonly string[]) {
	return arr.toSorted().map((val) => ({ value: val, label: val }));
}
export const genderOptions = enumToOption(genderEnum);
export const gradesOptions = enumToOption(gradesEnum);
export const doctorateTypeOptions = enumToOption(doctorateTypeEnum);
export const situationProfessionnelleOptions = enumToOption(situationProfessionnelleEnum);
export const domainOptions = enumToOption(domainEnum);
export const filiereOptions = enumToOption(filiereEnum);
export const laboratoiteRattachementOptions = enumToOption(laboratoiteRattachementEnum);
export const establishmentOptions = enumToOption(establishmentEnum);
